# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171116_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=15)),
                ('post', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='id',
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='login',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='password',
            field=models.TextField(max_length=15),
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Sign_up'),
        ),
    ]
