# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171118_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
