# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171119_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
